### PR TITLE
Add extra profile example

### PR DESCRIPTION
**Pull request by RobJN**
Add an even easier profile example. This is one where there is no dataset function as we load the data in directly from a json file.

### CODE REVIEW

**Comment by RobJN** [comment]
@Zverik If you accept this PR then can I recommend that the wiki is updated to link to this as the starting point. Currently it reads:

> Do study these, starting with the moscow_parkomats.py

A usage example would also be good here.

p.s. I am a complete idiot so it took me ages to figure this out!! A clearer wiki page would help others who are equally less skilled as I am.

**Comment by nlehuby** [comment]
I think you should also add the json file (or an extract of the json file) so the user can reproduce and study a fully working case, before quickstarting his own profile.

**Comment by RobJN** [comment]
I didn't because the wiki laid out the json format for all the see. I can
add it though if that's what the consensus is. Might be a few days...

**Comment by Zverik** [comment]
Thanks for this pull request!
Sorry I don't merge it: instead I've just published five more profile examples, [one of which](https://github.com/mapsme/osm_conflate/blob/master/profiles/navads_shell.py) does the same.

**Comment by RobJN** [comment]
Perfect. Thanks.

**Pull request closed without merging**
